"$schema" = "schemas/schema.json"

[default]
description = "Default permissions for the icloud-container plugin."
permissions = [
  "allow-get-container-status",
  "allow-get-container-url",
  "allow-read-file",
  "allow-write-file",
  "allow-create-file",
  "allow-item-exists",
  "allow-get-attributes",
  "allow-create-directory",
  "allow-list-directory",
  "allow-delete-item",
  "allow-trash-item",
  "allow-move-item",
  "allow-copy-item",
  "allow-get-item-sync-status",
  "allow-start-download",
  "allow-evict-item",
  "allow-is-ubiquitous",
  "allow-watch-directory",
  "allow-unwatch",
  "allow-watch-file",
  "allow-unwatch-file",
]
